name: Checkout
on: [push]

jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: List files Before
              run: ls -a
            - uses: actions/checkout@v4
            - name: List files After
              run: ls -a