name: Expressions & Contexts
on: [push, workflow_dispatch]
run-name: "Expression & Contexts by @${{ github.actor }}, event: ${{ github.event_name }}"

jobs:
    using-exprsssions-and-contexts:
        runs-on: ubuntu-latest
        if: github.event == 'push'
        steps:
            - name: Expressions
              id: expressions
              run: |
                echo ${{ 1 }}
                echo ${{ 'This is a string' }}
                echo ${{ true }}
            - name: Dump Contexts
              run: |
                echo '${{ toJson(github) }}'
                echo '${{ toJson(job) }}'
                echo '${{ toJson(secrets) }}'
                echo '${{ toJson(steps) }}'
                echo '${{ toJson(runner) }}'