name: Manually Triggered
on:
    workflow_dispatch:
        inputs:
            string:
                description: A string Input
                type: string
                required: true
                default: "Default value"
            number:
                description: A number input
                default: 4
                type: number
jobs:
    log-info:
        runs-on: ubuntu-latest
        steps:
            - run: echo $GITHUB_REF
            - run: |
                echo "String: ${{ inputs.string }}"
                echo "Number: ${{ inputs.number }}"

