name: Slack
on: [push]

jobs:
    slack-job:
        runs-on: ubuntu-latest
        container: 
        steps:
        - name: Send a slack message
          uses: docker://technosophos/slack-notify
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_TITLE: "From Github Actions"
            SLACK_MESSAGE: "Actor: ${{github.actor}}, Event: ${{github.event_name}}"
            SLACK_COLOR: "#723fc4"